-- ASSOCARO TABLE
-- ASSOCiation of the ARrival and Origin tables
-- Direct copy from the CISN / AQMS parametric schema implemented
-- for PostgreSQL database backed AQMS installations. Editor added this header block.
-- Author: Renate Hartog
-- Editor: Nathan T. Stevens
-- org: PNSN / AQMS-SWG
-- license: CC 1.0

 CREATE TABLE ASSOCARO 
 (	ORID BIGINT, 
	ARID BIGINT, 
	COMMID BIGINT, 
	AUTH VARCHAR(15) NOT NULL , 
	SUBSOURCE VARCHAR(8), 
	IPHASE VARCHAR(8), 
	IMPORTANCE DOUBLE PRECISION, 
	DELTA DOUBLE PRECISION, 
	SEAZ DOUBLE PRECISION, 
	IN_WGT DOUBLE PRECISION, 
	WGT DOUBLE PRECISION, 
	TIMERES DOUBLE PRECISION, 
	EMA DOUBLE PRECISION, 
	SLOW DOUBLE PRECISION, 
	VMODELID SMALLINT, 
	SCORR DOUBLE PRECISION, 
	SDELAY DOUBLE PRECISION, 
	RFLAG VARCHAR(2), 
	CCSET SMALLINT, 
	LDDATE TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'
       ), 
	 CONSTRAINT ASSOCARO04 CHECK (importance >= 0.0 and importance <= 1.0) , 
	 CONSTRAINT ASSOCARO02 CHECK (delta >= 0.0) , 
	 CONSTRAINT ASSOCARO05 CHECK (seaz >= 0.0 and seaz <= 360.0) , 
	 CONSTRAINT ASSOCARO06 CHECK (SLOW>=0.0) , 
	 CONSTRAINT ASSOCARO09 CHECK (ccset < 1) , 
	 CONSTRAINT ASSOCARO10 CHECK (rflag in ('a','h','f','A','H','F')) , 
	 CONSTRAINT ASSOCAROKEY01 PRIMARY KEY (ORID, ARID) 
 ); 