 CREATE TABLE ASSOCCOM 
 (	MAGID BIGINT, 
	COID BIGINT, 
	COMMID BIGINT, 
	AUTH VARCHAR(15) NOT NULL , 
	SUBSOURCE VARCHAR(8), 
	WEIGHT DOUBLE PRECISION, 
	IN_WGT DOUBLE PRECISION, 
	RFLAG VARCHAR(2), 
	MAG DOUBLE PRECISION, 
	MAGRES DOUBLE PRECISION, 
	MAGCORR DOUBLE PRECISION, 
	LDDATE TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'), 
	 CONSTRAINT ASSOCCOMKEY04 CHECK (weight >= 0.0 and weight <= 1.0) , 
	 CONSTRAINT ASSOCCOMKEY05 CHECK (in_wgt >= 0.0 and in_wgt <= 1.0) , 
	 CONSTRAINT ASSOCCOMKEY06 CHECK (rflag in ('a','h','f','A','H','F')) , 
	 CONSTRAINT ASSOCCOMKEY01 PRIMARY KEY (MAGID, COID) 
 ); 
