CREATE TABLE WFPROC
    WFPID BIGINT,
    NAME VARCHAR(80),
    INTERPRETER VARCHAR(80) NOT NULL,
    LIBRARY VARHCAR(80) NOT NULL,
    METHOD VARCHAR(80) NOT NULL,
    KWARGS TEXT[][],
    COMMID BIGINT,
